version: '3.7'
services:

  haxcms:
    build:
      context: .
    image: <%= name %>_haxcms:${CI_COMMIT_SHORT_SHA:-latest}
    # volumes:
    #   - /var/www/html/dist
    #   - /var/www/html/build
    #   - .:/var/www/html/
    networks:
      - traefik-public
    labels:
      - "traefik.enabled=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:<%= name %>.${HOST:-docker.localhost}"
    deploy:
      labels:
        - "traefik.enabled=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:<%= name %>.${HOST:-docker.localhost}"
        - "traefik.tag=traefik-public"
      replicas: 1
      update_config:
        order: start-first

networks:
  traefik-public:
    external: true