version: '3.7'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    networks:
      - traefik-public
    ports:
      - "80:80"     # The HTTP port
      # - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  haxcms:
    volumes:
      - ./:/var/www/html/_sites/<%= name %>:delegated
      - ./_config:/var/www/html/_config:delegated
      - ./custom:/var/www/html/_sites/<%= name %>/custom:delegated

  vscode:
    volumes:
      - ./:/home/coder/project/<%= name %>:delegated
      - ./custom:/home/coder/project/<%= name %>/custom:delegated
      # - ~/.ssh:/root/.ssh:ro

  custom:
    volumes:
      - ./custom:/home/node/app:delegated

networks:
  traefik-public: